[package]
name = "BunnyFrac"
version = "0.1.0"
authors = ["Kate"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-complex = "0.3"
image = "0.23"